### ISSUE TITLE
Please fix

### ISSUE THREAD

**Issue by gkjoyes** [evalphobia/logrus_fluent#26]
--> `evalphobia/logrus_fluent/config.go:49:8` : unknown field 'Async' in struct literal of type fluent.Config

**Comment by evalphobia** [comment]
@g-kutty 
It's changed by from https://github.com/evalphobia/logrus_fluent/pull/25

So please update `github.com/fluent/fluent-logger-golang` library version OR use `v0.4.0`.

**Comment by gkjoyes** [comment]
Ok, thank you.

**Comment by CreativeCactus** [comment]
Neither of these solutions worked for me. I tried both the latest `fluent-logger-golang` (1.3.0) and using version 0.4.0 of `logrus_fluent`. I am using dep to deploy in docker. Can you offer a more detailed explanation of the fix, please?

**Comment by evalphobia** [comment]
@CreativeCactus  You should use the version combinations below,

- `fluent-logger-golang:v1.3.0~` & `logrus_fluent:v0.5.0~`
- `fluent-logger-golang:~v1.2.1` & `logrus_fluent:~v0.4.0`
